#' Constructor for fastrerandomize randomizations
#'
#' @description
#' Create an S3 object of class \code{fastrerandomize_instance} that stores
#' the randomizations (and optionally balance statistics) generated by 
#' functions such as \code{\link{generate_randomizations}}.
#'
#' @param randomizations A matrix or array where each row (or slice) represents one 
#'   randomization.
#' @param balance A numeric vector or similar object holding balance statistics 
#'   for each randomization, or \code{NULL} if not applicable.
#' @param call The function call, if you wish to store it for reference (optional).
#'
#' @return An object of class \code{fastrerandomize_instance}.
#'
#' @export
fastrerandomize_class <- function(randomizations, balance = NULL, call = NULL) {
  structure(
    list(
      randomizations = randomizations,
      balance = balance,
      call = call
    ),
    class = "fastrerandomize_instance"
  )
}

#' Print method for fastrerandomize_instance objects
#'
#' @param x An object of class \code{fastrerandomize_instance}.
#' @param ... Further arguments passed to or from other methods.
#'
#' @export
print.fastrerandomize_instance <- function(x, ...) {
  cat("Object of class 'fastrerandomize_instance'\n\n")
  
  if (!is.null(x$call)) {
    cat("Call:\n  ", paste(deparse(x$call), collapse = "\n  "), "\n\n")
  }
  
  # Basic info about randomizations
  if (is.null(x$randomizations)) {
    cat("No randomizations stored.\n")
  } else {
    # For matrices/arrays: 
    cat("Number of candidate randomizations:", nrow(x$randomizations), "\n")
    cat("Number of units (columns):", ncol(x$randomizations), "\n")
  }
  
  # Balance info if available
  if (!is.null(x$balance)) {
    cat("Balance statistics available for each randomization.\n")
  }
  
  invisible(x)
}

#' Summary method for fastrerandomize_instance objects
#'
#' @param object An object of class \code{fastrerandomize_instance}.
#' @param ... Further arguments passed to or from other methods.
#'
#' @return A list with summary statistics, printed by default.
#'
#' @export
summary.fastrerandomize_instance <- function(object, ...) {
  cat("Summary of 'fastrerandomize_instance' object:\n\n")
  
  if (!is.null(object$balance)) {
    # Provide some numeric summary:
    bal_stats <- summary(object$balance)
    cat("Balance statistics (summary):\n")
    print(bal_stats)
  } else {
    cat("No balance statistics found.\n")
  }
  
  # Optionally return an invisible list for programmatic use
  invisible(list(
    call = object$call,
    num_randomizations = nrow(object$randomizations),
    balance_summary = if (!is.null(object$balance)) summary(object$balance)
  ))
}

#' Plot method for fastrerandomize_instance objects
#'
#' @param x An object of class \code{fastrerandomize_instance}.
#' @param ... Further arguments passed to base \code{\link{plot}} functions.
#'
#' @export
plot.fastrerandomize_instance <- function(x, ...) {
  if (is.null(x$balance)) {
    message("No balance data in this randomization object. Nothing to plot.")
    return(invisible(NULL))
  }
  hist(
    x$balance, 
    main = "Distribution of Balance Measures",
    xlab = "Balance Measure",
    col = "steelblue", 
    ...
  )
}


